//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myblazorapp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myblazorapp.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string aboutPageLastModStr {
            get {
                return ResourceManager.GetString("aboutPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutTitlePageStr {
            get {
                return ResourceManager.GetString("aboutTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string contactPageLastModStr {
            get {
                return ResourceManager.GetString("contactPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactPageTitleStr {
            get {
                return ResourceManager.GetString("contactPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my (GustafU233C) website contact page!.
        /// </summary>
        public static string contactPageWelcomeStr {
            get {
                return ResourceManager.GetString("contactPageWelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Me.
        /// </summary>
        public static string counterPageClickMeBtnStr {
            get {
                return ResourceManager.GetString("counterPageClickMeBtnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Count:.
        /// </summary>
        public static string counterPageCurrentCountStr {
            get {
                return ResourceManager.GetString("counterPageCurrentCountStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string counterPageLastModStr {
            get {
                return ResourceManager.GetString("counterPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string counterPageTitleStr {
            get {
                return ResourceManager.GetString("counterPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string donatePageLastModStr {
            get {
                return ResourceManager.GetString("donatePageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string donatePageTitleStr {
            get {
                return ResourceManager.GetString("donatePageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string EulaPageLastModStr {
            get {
                return ResourceManager.GetString("EulaPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreement.
        /// </summary>
        public static string EulaTitlePageStr {
            get {
                return ResourceManager.GetString("EulaTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string indexLastModStr {
            get {
                return ResourceManager.GetString("indexLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will be using this website to discuss / share my thoughts and open source work on GitHub..
        /// </summary>
        public static string indexParaOneStr {
            get {
                return ResourceManager.GetString("indexParaOneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on the .NET Blazor project and or it&apos;s associated projects, please click the &quot;About .NET Blazor&quot; link in the top right corner of the site!.
        /// </summary>
        public static string IndexParaThreeStr {
            get {
                return ResourceManager.GetString("IndexParaThreeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is generously hosted by GitHub Pages, and powered by .NET Blazor..
        /// </summary>
        public static string indexParaTwoStr {
            get {
                return ResourceManager.GetString("indexParaTwoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string indexWelcomeStr {
            get {
                return ResourceManager.GetString("indexWelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my (GustafU233C) website!.
        /// </summary>
        public static string indexWelcomeToStr {
            get {
                return ResourceManager.GetString("indexWelcomeToStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified:.
        /// </summary>
        public static string lastModifiedStr {
            get {
                return ResourceManager.GetString("lastModifiedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string legalPageLastModStr {
            get {
                return ResourceManager.GetString("legalPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Affairs.
        /// </summary>
        public static string legalPageTitleStr {
            get {
                return ResourceManager.GetString("legalPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string navBarAboutStr {
            get {
                return ResourceManager.GetString("navBarAboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string navBarContactStr {
            get {
                return ResourceManager.GetString("navBarContactStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string navBarCounterStr {
            get {
                return ResourceManager.GetString("navBarCounterStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string navBarDonateStr {
            get {
                return ResourceManager.GetString("navBarDonateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Examples.
        /// </summary>
        public static string navBarDotnetExamplesStr {
            get {
                return ResourceManager.GetString("navBarDotnetExamplesStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULA.
        /// </summary>
        public static string navBarEulaStr {
            get {
                return ResourceManager.GetString("navBarEulaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        public static string navBarFetchDataStr {
            get {
                return ResourceManager.GetString("navBarFetchDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string navBarHomeStr {
            get {
                return ResourceManager.GetString("navBarHomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Affairs.
        /// </summary>
        public static string navBarLegalAffairsStr {
            get {
                return ResourceManager.GetString("navBarLegalAffairsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string navBarPrivacyPolicyStr {
            get {
                return ResourceManager.GetString("navBarPrivacyPolicyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string navBarTaConStr {
            get {
                return ResourceManager.GetString("navBarTaConStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string navBarToServePageStr {
            get {
                return ResourceManager.GetString("navBarToServePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string privacyPageLastModStr {
            get {
                return ResourceManager.GetString("privacyPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacyPageTitleStr {
            get {
                return ResourceManager.GetString("privacyPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string TaConPageLastModStr {
            get {
                return ResourceManager.GetString("TaConPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TaConTitlePageStr {
            get {
                return ResourceManager.GetString("TaConTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string TofServPageLastModStr {
            get {
                return ResourceManager.GetString("TofServPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TofServTitlePageStr {
            get {
                return ResourceManager.GetString("TofServTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .NET Blazor.
        /// </summary>
        public static string topRowAboutDotnetStr {
            get {
                return ResourceManager.GetString("topRowAboutDotnetStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string topRowLanguageSelectStr {
            get {
                return ResourceManager.GetString("topRowLanguageSelectStr", resourceCulture);
            }
        }
    }
}
