//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myblazorapp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myblazorapp.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string aboutPageLastModStr {
            get {
                return ResourceManager.GetString("aboutPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutTitlePageStr {
            get {
                return ResourceManager.GetString("aboutTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should you have any questions, concerns, and or would like to offer any advice, please feel free to email me at: GustafU233C@Protonmail.com..
        /// </summary>
        public static string contactPageFirstParaStr {
            get {
                return ResourceManager.GetString("contactPageFirstParaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: July 20, 2023.
        /// </summary>
        public static string contactPageLastModStr {
            get {
                return ResourceManager.GetString("contactPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information Details:.
        /// </summary>
        public static string contactPageSecondTitleStr {
            get {
                return ResourceManager.GetString("contactPageSecondTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactPageTitleStr {
            get {
                return ResourceManager.GetString("contactPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my (GustafU233C) website contact page!.
        /// </summary>
        public static string contactPageWelcomeStr {
            get {
                return ResourceManager.GetString("contactPageWelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Me.
        /// </summary>
        public static string counterPageClickMeBtnStr {
            get {
                return ResourceManager.GetString("counterPageClickMeBtnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Count:.
        /// </summary>
        public static string counterPageCurrentCountStr {
            get {
                return ResourceManager.GetString("counterPageCurrentCountStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string counterPageLastModStr {
            get {
                return ResourceManager.GetString("counterPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string counterPageTitleStr {
            get {
                return ResourceManager.GetString("counterPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string donatePageLastModStr {
            get {
                return ResourceManager.GetString("donatePageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string donatePageTitleStr {
            get {
                return ResourceManager.GetString("donatePageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string EulaPageLastModStr {
            get {
                return ResourceManager.GetString("EulaPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Licence Agreement.
        /// </summary>
        public static string EulaTitlePageStr {
            get {
                return ResourceManager.GetString("EulaTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string indexLastModStr {
            get {
                return ResourceManager.GetString("indexLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will be using this website to discuss / share my thoughts and open source work on GitHub..
        /// </summary>
        public static string indexParaOneStr {
            get {
                return ResourceManager.GetString("indexParaOneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on the .NET Blazor project and or it&apos;s associated projects, please click the &quot;About .NET Blazor&quot; link in the top right corner of the site!.
        /// </summary>
        public static string IndexParaThreeStr {
            get {
                return ResourceManager.GetString("IndexParaThreeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is generously hosted by GitHub Pages, and powered by .NET Blazor..
        /// </summary>
        public static string indexParaTwoStr {
            get {
                return ResourceManager.GetString("indexParaTwoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string indexWelcomeStr {
            get {
                return ResourceManager.GetString("indexWelcomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my (GustafU233C) website!.
        /// </summary>
        public static string indexWelcomeToStr {
            get {
                return ResourceManager.GetString("indexWelcomeToStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified:.
        /// </summary>
        public static string lastModifiedStr {
            get {
                return ResourceManager.GetString("lastModifiedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string legalPageLastModStr {
            get {
                return ResourceManager.GetString("legalPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Affairs.
        /// </summary>
        public static string legalPageTitleStr {
            get {
                return ResourceManager.GetString("legalPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date: July 20, 2023.
        /// </summary>
        public static string licenseEffectiveDateStr {
            get {
                return ResourceManager.GetString("licenseEffectiveDateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This licence (hereinafter referred to as the “Licence”) was originally prepared in the English language. Although GustafU233C may provide one or more translated versions of this Licence, for your convenience, and or as required by municipal, and or provincial, and or state, and or federal law, it is very important to note that the English language version of this Licence will always be the sole governing version of this Licence, in the case of any conflict and or discrepancy and or dispute, legal in nature  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string licenseLanguageClarifyStr {
            get {
                return ResourceManager.GetString("licenseLanguageClarifyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: July 20, 2023.
        /// </summary>
        public static string licensePageLastModStr {
            get {
                return ResourceManager.GetString("licensePageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With regard to the underlying source code for the website presented at: https://gustafu233c.github.io/gustafu233c/, and contained in official repository at: https://github.com/GustafU233C/gustafu233c, the following Licence applies..
        /// </summary>
        public static string licenseParagraph1Str {
            get {
                return ResourceManager.GetString("licenseParagraph1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT Licence.
        /// </summary>
        public static string licenseParagraph2Str {
            get {
                return ResourceManager.GetString("licenseParagraph2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2023 GustafU233C.
        /// </summary>
        public static string licenseParagraph3Str {
            get {
                return ResourceManager.GetString("licenseParagraph3Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string licenseParagraph4Str {
            get {
                return ResourceManager.GetString("licenseParagraph4Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:.
        /// </summary>
        public static string licenseParagraph5Str {
            get {
                return ResourceManager.GetString("licenseParagraph5Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software..
        /// </summary>
        public static string licenseParagraph6Str {
            get {
                return ResourceManager.GetString("licenseParagraph6Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE..
        /// </summary>
        public static string licenseParagraph7Str {
            get {
                return ResourceManager.GetString("licenseParagraph7Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string licenseTitlePageStr {
            get {
                return ResourceManager.GetString("licenseTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string navBarAboutStr {
            get {
                return ResourceManager.GetString("navBarAboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string navBarContactStr {
            get {
                return ResourceManager.GetString("navBarContactStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string navBarCounterStr {
            get {
                return ResourceManager.GetString("navBarCounterStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string navBarDonateStr {
            get {
                return ResourceManager.GetString("navBarDonateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Examples.
        /// </summary>
        public static string navBarDotnetExamplesStr {
            get {
                return ResourceManager.GetString("navBarDotnetExamplesStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULA.
        /// </summary>
        public static string navBarEulaStr {
            get {
                return ResourceManager.GetString("navBarEulaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        public static string navBarFetchDataStr {
            get {
                return ResourceManager.GetString("navBarFetchDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string navBarHomeStr {
            get {
                return ResourceManager.GetString("navBarHomeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Affairs.
        /// </summary>
        public static string navBarLegalAffairsStr {
            get {
                return ResourceManager.GetString("navBarLegalAffairsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string navBarLicenseStr {
            get {
                return ResourceManager.GetString("navBarLicenseStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string navBarMenuExpandStr {
            get {
                return ResourceManager.GetString("navBarMenuExpandStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string navBarPrivacyPolicyStr {
            get {
                return ResourceManager.GetString("navBarPrivacyPolicyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string navBarProj1CommonProbsSubNavStr {
            get {
                return ResourceManager.GetString("navBarProj1CommonProbsSubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        public static string navBarProj1CommonProbsUTF8SubNavStr {
            get {
                return ResourceManager.GetString("navBarProj1CommonProbsUTF8SubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string navBarProj1HowToGenerallySubNavStr {
            get {
                return ResourceManager.GetString("navBarProj1HowToGenerallySubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To.
        /// </summary>
        public static string navBarProj1HowToSubNavStr {
            get {
                return ResourceManager.GetString("navBarProj1HowToSubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string navBarProj1OpenPackages1SubNavStr {
            get {
                return ResourceManager.GetString("navBarProj1OpenPackages1SubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string navBarProj1OpenPackagesSubNavStr {
            get {
                return ResourceManager.GetString("navBarProj1OpenPackagesSubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string navBarProj2AboutStr {
            get {
                return ResourceManager.GetString("navBarProj2AboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string navBarProj3AboutStr {
            get {
                return ResourceManager.GetString("navBarProj3AboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULA.
        /// </summary>
        public static string navBarProj3LegalAffSubNavEulaStr {
            get {
                return ResourceManager.GetString("navBarProj3LegalAffSubNavEulaStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string navBarProj3LegalAffSubNavPrivacyStr {
            get {
                return ResourceManager.GetString("navBarProj3LegalAffSubNavPrivacyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string navBarProj3LegalAffSubNavStr {
            get {
                return ResourceManager.GetString("navBarProj3LegalAffSubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string navBarProj3LegalAffSubNavTandConStr {
            get {
                return ResourceManager.GetString("navBarProj3LegalAffSubNavTandConStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string navBarProj3LegalAffSubNavTofServeStr {
            get {
                return ResourceManager.GetString("navBarProj3LegalAffSubNavTofServeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string navBarProj3PackagesSubNavPack1Str {
            get {
                return ResourceManager.GetString("navBarProj3PackagesSubNavPack1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string navBarProj3PackagesSubNavPack2Str {
            get {
                return ResourceManager.GetString("navBarProj3PackagesSubNavPack2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string navBarProj3PackagesSubNavPack3Str {
            get {
                return ResourceManager.GetString("navBarProj3PackagesSubNavPack3Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string navBarProject3PackagesSubNavStr {
            get {
                return ResourceManager.GetString("navBarProject3PackagesSubNavStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 4.
        /// </summary>
        public static string navBarProject4Str {
            get {
                return ResourceManager.GetString("navBarProject4Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 1.
        /// </summary>
        public static string navBarProjectOneStr {
            get {
                return ResourceManager.GetString("navBarProjectOneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string navBarProjectsStr {
            get {
                return ResourceManager.GetString("navBarProjectsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 3.
        /// </summary>
        public static string navBarProjectThreeStr {
            get {
                return ResourceManager.GetString("navBarProjectThreeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 2.
        /// </summary>
        public static string navBarProjectTwoStr {
            get {
                return ResourceManager.GetString("navBarProjectTwoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string navBarProjOneAboutStr {
            get {
                return ResourceManager.GetString("navBarProjOneAboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string navBarTaConStr {
            get {
                return ResourceManager.GetString("navBarTaConStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string navBarToServePageStr {
            get {
                return ResourceManager.GetString("navBarToServePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date: July 20, 2023.
        /// </summary>
        public static string privacyPageEffectiveStr {
            get {
                return ResourceManager.GetString("privacyPageEffectiveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the French translation of the current Privacy Policy is not yet available. Please see the English translation of the current Privacy Policy below. We are sorry for any inconvenience that this may cause..
        /// </summary>
        public static string privacyPageFrenchNoticeStr {
            get {
                return ResourceManager.GetString("privacyPageFrenchNoticeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: July 20, 2023.
        /// </summary>
        public static string privacyPageLastModStr {
            get {
                return ResourceManager.GetString("privacyPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We May Potentially Collect and or Use Your Personal Information and or Data:.
        /// </summary>
        public static string privacyPagePara10Str {
            get {
                return ResourceManager.GetString("privacyPagePara10Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide Our Services, We may potentially collect Data about you from a variety of sources, as set out below. The information that We may potentially collect, and or use varies depending on how you interact with Us and or Our Services and or Our Site..
        /// </summary>
        public static string privacyPagePara11Str {
            get {
                return ResourceManager.GetString("privacyPagePara11Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition to the specific uses set out below, We may also potentially use the Data We collect about you to communicate with you, and or provide Our Services, and or comply with any applicable legal obligations, and or enforce any applicable terms of service, and or to protect and or defend Our Services, Our Site, Our rights and or responsibilities, and or the rights and or responsibilities of Our users and or others..
        /// </summary>
        public static string privacyPagePara12Str {
            get {
                return ResourceManager.GetString("privacyPagePara12Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Personal Information and or Data We May Potentially Collect from You:.
        /// </summary>
        public static string privacyPagePara13Str {
            get {
                return ResourceManager.GetString("privacyPagePara13Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The types of personal information and or Data that We may obtain about you depends on how you interact with Our Site and or Our Services. When We use the term &quot;personal information&quot;, We are referring to information that identifies, relates to, describes and or can be associated with you. The following sections describe the categories and or specific types of personal information, and or Data, that We may potentially collect from you..
        /// </summary>
        public static string privacyPagePara14Str {
            get {
                return ResourceManager.GetString("privacyPagePara14Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and or Data We May Potentially Collect Directly from You:.
        /// </summary>
        public static string privacyPagePara15Str {
            get {
                return ResourceManager.GetString("privacyPagePara15Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and or Data that you directly submit to Us through Our Services may include:.
        /// </summary>
        public static string privacyPagePara16Str {
            get {
                return ResourceManager.GetString("privacyPagePara16Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic contact details: including, but not limited to, potentially your name, address, phone number and or email address..
        /// </summary>
        public static string privacyPagePara17Str {
            get {
                return ResourceManager.GetString("privacyPagePara17Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order information: including, but not limited to, potentially your name, billing address, shipping address, payment information, payment confirmation, email address, and or phone number..
        /// </summary>
        public static string privacyPagePara18Str {
            get {
                return ResourceManager.GetString("privacyPagePara18Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information: including, but not limited to, potentially your username, password, and or security questions..
        /// </summary>
        public static string privacyPagePara19Str {
            get {
                return ResourceManager.GetString("privacyPagePara19Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy policy describes how GustafU233C (hereinafter referred to as &quot;We&quot;, &quot;Us&quot;, and or &quot;Our&quot;) may potentially collect, use, and or disclose your personal information and or data (hereinafter referred to as “Data”) when you visit, and or use Our services, and or make a purchase (hereinafter referred to collectively, as &quot;Services&quot;) from: https://gustafu233c.github.io/gustafu233c/ (hereinafter referred to as the &quot;Site&quot;), and or otherwise communicate with Us. For the purposes of this privacy policy (herei [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara1Str {
            get {
                return ResourceManager.GetString("privacyPagePara1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping information: including, but not limited to, potentially the items you view, put in your cart and or add to your wish-list..
        /// </summary>
        public static string privacyPagePara20Str {
            get {
                return ResourceManager.GetString("privacyPagePara20Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer support information: including potentially any information that you choose to include in communications with Us, for example, when sending a message through Our Services, if available..
        /// </summary>
        public static string privacyPagePara21Str {
            get {
                return ResourceManager.GetString("privacyPagePara21Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is important to note, that some features of Our Services may require you to directly provide Us with certain information about yourself. You may elect not to provide this information and or Data, but doing so may prevent you from using and or accessing these features..
        /// </summary>
        public static string privacyPagePara22Str {
            get {
                return ResourceManager.GetString("privacyPagePara22Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and or Data that May Be Potentially Collected through Cookies:.
        /// </summary>
        public static string privacyPagePara23Str {
            get {
                return ResourceManager.GetString("privacyPagePara23Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may also automatically collect certain information about your interaction with Our Services and or Our Site (hereinafter referred to as &quot;Usage Data&quot;). To do this, We may use cookies, pixels and or similar technologies (hereinafter referred to as &quot;Cookies&quot;). Usage Data may potentially include information about how you access and or use Our Site and or Services and or your account, including, but not limited to: device information, browser information, information about your network connection, your IP add [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara24Str {
            get {
                return ResourceManager.GetString("privacyPagePara24Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and or Data We May Potentially Obtain from Third Parties:.
        /// </summary>
        public static string privacyPagePara25Str {
            get {
                return ResourceManager.GetString("privacyPagePara25Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may also potentially obtain information about you from third parties, including from vendors and or service providers who may collect information on Our behalf, such as:.
        /// </summary>
        public static string privacyPagePara26Str {
            get {
                return ResourceManager.GetString("privacyPagePara26Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies who may potentially support Our Site and or Our Services: a theoretical example could be a company such as Shopify..
        /// </summary>
        public static string privacyPagePara27Str {
            get {
                return ResourceManager.GetString("privacyPagePara27Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our potential payment processors: who may collect payment information (for example: bank account, credit and or debit card information, billing address, etc.) to process your payment in order to fulfill your orders and or provide you with products and or services you may have requested, in order to perform Our contract or contracts with you..
        /// </summary>
        public static string privacyPagePara28Str {
            get {
                return ResourceManager.GetString("privacyPagePara28Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you visit Our Site, open and or click on emails We may send to you, and or otherwise interact with Our Services and or advertisements, We, and or third parties We work with, may automatically collect certain information using online tracking technologies such as pixels, web beacons, software developer kits, third-party libraries and or Cookies..
        /// </summary>
        public static string privacyPagePara29Str {
            get {
                return ResourceManager.GetString("privacyPagePara29Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read this Privacy Policy carefully. By using and or accessing any of Our Services and or Our Site, you agree to the potential collection, use, and or disclosure of your Data as described in this Privacy Policy. If you do not agree with this Privacy Policy, do not use and or access any of Our Services and or Our Site..
        /// </summary>
        public static string privacyPagePara2Str {
            get {
                return ResourceManager.GetString("privacyPagePara2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any information We obtain from third parties will be treated in accordance with this Privacy Policy. We are not responsible and or liable for the accuracy of the information provided to Us by third parties and are not responsible for any third party&apos;s policies and or practices. For more information, see the section below labelled: Third Party Websites and or Links..
        /// </summary>
        public static string privacyPagePara30Str {
            get {
                return ResourceManager.GetString("privacyPagePara30Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We May Potentially Use Your Personal Information and or Data:.
        /// </summary>
        public static string privacyPagePara31Str {
            get {
                return ResourceManager.GetString("privacyPagePara31Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may potentially use your personal information and or Data when:.
        /// </summary>
        public static string privacyPagePara32Str {
            get {
                return ResourceManager.GetString("privacyPagePara32Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing Products and or Services. We may use your personal information and or Data to provide you with Our Services in order to perform Our contract and or contracts with you, including to process your potential payments, fulfill your potential orders, to send notifications to you related to your account, purchases, returns, exchanges and or other transactions, to create, maintain and or otherwise manage your account, to arrange for shipping, facilitate any returns and or exchanges, and or to enable you t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara33Str {
            get {
                return ResourceManager.GetString("privacyPagePara33Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing and or Advertising. We may potentially use your personal information and or Data for marketing and or promotional purposes, such as to send marketing, advertising and or promotional communications by email, text message and or postal mail, and or to show you advertisements for products and or services. This may include using your personal information and or Data to better tailor Our Services and or advertising on Our Site and or other websites and or other Services..
        /// </summary>
        public static string privacyPagePara34Str {
            get {
                return ResourceManager.GetString("privacyPagePara34Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security and or Fraud Protection. We may potentially use your personal information and or Data to detect, investigate and or take action regarding possible fraudulent, illegal and or malicious activity. If you choose to use Our Services and or register an account, you are responsible for keeping your account credentials safe. We highly recommend that you do not share your username, password, and or other access details with anyone else. If you believe your account has been compromised, please contact us imm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara35Str {
            get {
                return ResourceManager.GetString("privacyPagePara35Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicating with You. We may also potentially use your personal information and or Data to provide you with customer support and or otherwise improve Our Services and or Our Site. This is in Our legitimate interests in order to be responsive to you, to provide effective services to you, and or to maintain Our business relationship with you..
        /// </summary>
        public static string privacyPagePara36Str {
            get {
                return ResourceManager.GetString("privacyPagePara36Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We May Potentially Disclose Your Personal Information and or Data:.
        /// </summary>
        public static string privacyPagePara37Str {
            get {
                return ResourceManager.GetString("privacyPagePara37Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In certain circumstances, We may potentially disclose your personal information and or Data to third parties for legitimate purposes subject to this Privacy Policy. Such circumstances may include, but are not limited to:.
        /// </summary>
        public static string privacyPagePara38Str {
            get {
                return ResourceManager.GetString("privacyPagePara38Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With vendors and or other third parties who perform services on Our behalf (e.g., IT management, payment processing, data analytics, customer support, cloud storage, fulfillment and or shipping)..
        /// </summary>
        public static string privacyPagePara39Str {
            get {
                return ResourceManager.GetString("privacyPagePara39Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governing Law:.
        /// </summary>
        public static string privacyPagePara3Str {
            get {
                return ResourceManager.GetString("privacyPagePara3Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With business and or marketing partners, for example, with a company such as Shopify, to provide services and or advertisements to you. Our business and or marketing partners may potentially use your information in accordance with their own privacy policies..
        /// </summary>
        public static string privacyPagePara40Str {
            get {
                return ResourceManager.GetString("privacyPagePara40Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you direct, request Us and or otherwise consent to Our disclosure of certain information to third parties, such as to ship you products and or through your use of social media widgets and or login integration&apos;s, with your consent..
        /// </summary>
        public static string privacyPagePara41Str {
            get {
                return ResourceManager.GetString("privacyPagePara41Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Our affiliates and or otherwise within Our corporate group, in Our legitimate interests to run a successful business..
        /// </summary>
        public static string privacyPagePara42Str {
            get {
                return ResourceManager.GetString("privacyPagePara42Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In connection with a business transaction, such as a merger and or bankruptcy, to comply with any applicable legal obligations (including to respond to subpoenas, search warrants and or similar requests), to enforce any applicable terms of service, and or to protect and or defend Our Services, Our Site, Our rights, and or the rights of Our users and or others..
        /// </summary>
        public static string privacyPagePara43Str {
            get {
                return ResourceManager.GetString("privacyPagePara43Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Generated Content:.
        /// </summary>
        public static string privacyPagePara44Str {
            get {
                return ResourceManager.GetString("privacyPagePara44Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services may enable you with the ability to post product reviews and or other user-generated content. If you choose to submit user-generated content to any public area of Our Services, and or Our Site, this content will be public and or accessible by anyone..
        /// </summary>
        public static string privacyPagePara45Str {
            get {
                return ResourceManager.GetString("privacyPagePara45Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not control who will have access to the information and or Data that you may choose to make available to others, and We cannot ensure that parties who have access to such information and or Data will respect your privacy and or keep it secure. We are not responsible for the privacy and or security of any information and or Data that you may choose to make publicly available, and or for the accuracy, use and or misuse of any information that you may disclose and or receive from third parties..
        /// </summary>
        public static string privacyPagePara46Str {
            get {
                return ResourceManager.GetString("privacyPagePara46Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Websites and or Links:.
        /// </summary>
        public static string privacyPagePara47Str {
            get {
                return ResourceManager.GetString("privacyPagePara47Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Site and or Our Services may provide links to websites and or other online platforms operated by third parties. If you follow links to sites not affiliated and or controlled by Us, you should review their privacy and or security policies and or other terms and conditions. We do not guarantee and are not responsible for the privacy and or security of such sites, including the accuracy, completeness, and or reliability of the information found on these sites. Information that you may provide on public and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara48Str {
            get {
                return ResourceManager.GetString("privacyPagePara48Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Personal Information and or Data:.
        /// </summary>
        public static string privacyPagePara49Str {
            get {
                return ResourceManager.GetString("privacyPagePara49Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The law governing this Privacy Policy and or any dispute in relation to this Privacy Policy will be the substantive law of the Province of Ontario, Canada, without regard to the choice of laws principles. In the context of this Privacy Policy, a dispute is defined as, but not solely limited to, a disagreement and or lacking of agreement between parties, that may result in any sort of action, be that action legal in nature or otherwise..
        /// </summary>
        public static string privacyPagePara4Str {
            get {
                return ResourceManager.GetString("privacyPagePara4Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services and or Our Site are not intended to be used by children, and We do not knowingly collect any personal information and or Data about children. If you are the parent and or guardian of a child who has potentially provided Us with their personal information and or Data, you may contact Us using the contact information details set out below to request that the personal information and or Data be deleted..
        /// </summary>
        public static string privacyPagePara50Str {
            get {
                return ResourceManager.GetString("privacyPagePara50Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of the “Effective Date” of this Privacy Policy, We do not have actual knowledge that We “collect”, &quot;share&quot; and or &quot;sell&quot; (as those terms are defined in applicable law) personal information of individuals under 16 years of age..
        /// </summary>
        public static string privacyPagePara51Str {
            get {
                return ResourceManager.GetString("privacyPagePara51Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security and or Retention of Your Personal Information and or Data:.
        /// </summary>
        public static string privacyPagePara52Str {
            get {
                return ResourceManager.GetString("privacyPagePara52Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that no security measures are perfect and or impenetrable, and We cannot guarantee &quot;perfect security&quot;. In addition, any information you send to Us may not be secure while in transit. We recommend that you do not use insecure channels to communicate sensitive and or confidential information to Us..
        /// </summary>
        public static string privacyPagePara53Str {
            get {
                return ResourceManager.GetString("privacyPagePara53Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long We retain your personal information and or Data depends on different factors, such as whether We need the information and or Data to maintain your account, to provide Our Services, comply with legal obligations, resolve disputes and or enforce other applicable contracts and or policies..
        /// </summary>
        public static string privacyPagePara54Str {
            get {
                return ResourceManager.GetString("privacyPagePara54Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Rights and or Responsibilities and or Choices:.
        /// </summary>
        public static string privacyPagePara55Str {
            get {
                return ResourceManager.GetString("privacyPagePara55Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on where you live, you may have some and or all of the rights listed below in relation to your personal information and or Data. However, these rights are not absolute, and or may apply only in certain circumstances, and or, in certain cases, We may decline your request as permitted by law..
        /// </summary>
        public static string privacyPagePara56Str {
            get {
                return ResourceManager.GetString("privacyPagePara56Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Access and or Know. You may have a right to request access to personal information and or Data that We may potentially hold about you, including details relating to the ways in which We use and or share your personal information and or Data..
        /// </summary>
        public static string privacyPagePara57Str {
            get {
                return ResourceManager.GetString("privacyPagePara57Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Delete. You may have a right to request that We delete personal information and or Data that We maintain about you..
        /// </summary>
        public static string privacyPagePara58Str {
            get {
                return ResourceManager.GetString("privacyPagePara58Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Correct. You may have a right to request that We correct potentially inaccurate personal information and or Data that We may potentially maintain about you..
        /// </summary>
        public static string privacyPagePara59Str {
            get {
                return ResourceManager.GetString("privacyPagePara59Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistic Interpretation of this Privacy Policy:.
        /// </summary>
        public static string privacyPagePara5Str {
            get {
                return ResourceManager.GetString("privacyPagePara5Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right of Portability. You may have a right to receive a copy of the personal information and or Data that We may potentially hold about you and or to request that We transfer it to a third party, in certain circumstances and or with certain exceptions..
        /// </summary>
        public static string privacyPagePara60Str {
            get {
                return ResourceManager.GetString("privacyPagePara60Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Opt out of Sale and or Sharing and or Targeted Advertising. You may have a right to direct Us not to &quot;sell&quot; and or &quot;share&quot; your personal information and or Data, and or, to opt out of the processing of your personal information and or Data for purposes considered to be &quot;targeted advertising&quot;, as defined in applicable privacy laws. Please note that if you visit Our Site with the Global Privacy Control opt-out preference signal enabled, depending on where you are, We will automatically treat this as  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara61Str {
            get {
                return ResourceManager.GetString("privacyPagePara61Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Limit and or Opt out of Use and or Disclosure of Sensitive Personal Information. You may have a right to direct Us to limit Our use and or disclosure of sensitive personal information and or Data to only what is necessary to perform Our Services and or provide the goods reasonably expected by an average individual..
        /// </summary>
        public static string privacyPagePara62Str {
            get {
                return ResourceManager.GetString("privacyPagePara62Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction of Processing. You may have the right to ask Us to stop and or restrict Our processing of your personal information and or Data..
        /// </summary>
        public static string privacyPagePara63Str {
            get {
                return ResourceManager.GetString("privacyPagePara63Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal of Consent. Where We rely on consent to process your personal information and or Data, you may have the right to withdraw this consent..
        /// </summary>
        public static string privacyPagePara64Str {
            get {
                return ResourceManager.GetString("privacyPagePara64Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appeal. You may have a right to appeal Our decision and or decisions if We decline to process your request. You can do so by replying directly to Our denial..
        /// </summary>
        public static string privacyPagePara65Str {
            get {
                return ResourceManager.GetString("privacyPagePara65Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing Communication Preferences. We may send you promotional emails, and you may opt out of receiving these at any time by using the unsubscribe option displayed in Our emails to you. If you opt out, We may still send you non-promotional emails, such as those about your account and or orders that you may have made..
        /// </summary>
        public static string privacyPagePara66Str {
            get {
                return ResourceManager.GetString("privacyPagePara66Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may potentially exercise any of these rights where indicated on Our Site and or by contacting Us using the contact information details provided below..
        /// </summary>
        public static string privacyPagePara67Str {
            get {
                return ResourceManager.GetString("privacyPagePara67Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will not discriminate against you for exercising any of these rights. We may need to collect information from you to verify your identity, such as your email address and or account information, before providing a substantive response to a request. In accordance with applicable laws, you may designate an authorized agent to make requests on your behalf to exercise your rights. Before accepting such a request from an agent, We will require that the agent provide proof that you have authorized them to act o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara68Str {
            get {
                return ResourceManager.GetString("privacyPagePara68Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International User’s Personal Information and or Data:.
        /// </summary>
        public static string privacyPagePara69Str {
            get {
                return ResourceManager.GetString("privacyPagePara69Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Privacy Policy was originally prepared in the English language. Although GustafU233C may provide one or more translated versions of this Privacy Policy, for your convenience, and or as required by municipal, and or provincial, and or state, and or federal law, it is very important to note that the English language version of this Privacy Policy will always be the sole governing version of this Privacy Policy, in the case of any conflict and or discrepancy and or dispute, legal in nature or otherwise. I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara6Str {
            get {
                return ResourceManager.GetString("privacyPagePara6Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that We may transfer, store and or process your personal information and or Data outside of the country that you currently live in, including the United States of America. Your personal information and or Data may also potentially be processed by staff and or third party service providers and or Our partners in these countries..
        /// </summary>
        public static string privacyPagePara70Str {
            get {
                return ResourceManager.GetString("privacyPagePara70Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If We transfer your personal information and or Data out of Europe, We will rely on recognized transfer mechanisms like the European Commission&apos;s Standard Contractual Clauses, and or any equivalent contracts issued by the relevant competent authority of the United Kingdom of Great Britain and Northern Ireland, as relevant, unless the data transfer is to a country that has been determined to provide an adequate level of protection..
        /// </summary>
        public static string privacyPagePara71Str {
            get {
                return ResourceManager.GetString("privacyPagePara71Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Personal Information and or Data Collection, and or Cookie Policy:.
        /// </summary>
        public static string privacyPagePara72Str {
            get {
                return ResourceManager.GetString("privacyPagePara72Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notwithstanding any and or all of the above information in this Privacy Policy, as of the “Effective Date” listed above, We do not knowingly collect and or use any Data from users and or potential users of Our Site and or Services. We also, as of the “Effective Date” listed above, do not use Cookies on Our Site. If we learn that We have collected any Data from an user and or a potential user, in breach of this Privacy Policy, the data will be deleted as soon as is possible, as required under applicable law..
        /// </summary>
        public static string privacyPagePara73Str {
            get {
                return ResourceManager.GetString("privacyPagePara73Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints:.
        /// </summary>
        public static string privacyPagePara74Str {
            get {
                return ResourceManager.GetString("privacyPagePara74Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any complaints about how We may potentially process your personal information and or Data, please feel free to contact Us using the contact information details provided below. If you are not satisfied with Our response to your complaint, depending on where you live, you may have the right to appeal Our decision by contacting Us again using the contact information details set out below for further clarification, and or, you may also have the right to lodge your complaint with your local data prot [rest of string was truncated]&quot;;.
        /// </summary>
        public static string privacyPagePara75Str {
            get {
                return ResourceManager.GetString("privacyPagePara75Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severability:.
        /// </summary>
        public static string privacyPagePara76Str {
            get {
                return ResourceManager.GetString("privacyPagePara76Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If at any time any of the provisions set forth in this Privacy Policy are found to be inconsistent and or invalid under applicable laws, those provisions will be deemed void and will be removed from this Privacy Policy. All other provisions will not be affected by the removal, and the rest of this Privacy Policy will still be considered valid..
        /// </summary>
        public static string privacyPagePara77Str {
            get {
                return ResourceManager.GetString("privacyPagePara77Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information Details:.
        /// </summary>
        public static string privacyPagePara78Str {
            get {
                return ResourceManager.GetString("privacyPagePara78Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should you have any questions and or concerns about Our Privacy Policy and or privacy practices, and or if you would like to exercise any of the rights potentially available to you, please email Us at: GustafU233C@Protonmail.com..
        /// </summary>
        public static string privacyPagePara79Str {
            get {
                return ResourceManager.GetString("privacyPagePara79Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With regard to gender in relation to the language used in this Privacy Policy, please note that the headings used in this Privacy Policy do not affect its interpretation. The use of any gender includes all genders. The singular includes the plural and vice-versa. Where a word and or phrase is defined, its’ other grammatical form and or forms have an equal and or corresponding meaning. If one gender has been utilized anywhere in this Privacy Policy, this is just for simplicity purposes only..
        /// </summary>
        public static string privacyPagePara7Str {
            get {
                return ResourceManager.GetString("privacyPagePara7Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes and or Modifications to this Privacy Policy:.
        /// </summary>
        public static string privacyPagePara8Str {
            get {
                return ResourceManager.GetString("privacyPagePara8Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may update this Privacy Policy from time to time, including to reflect changes to Our current practices and or for other operational, legal, and or regulatory reasons. We will post the revised Privacy Policy on Our Site, update the &quot;Effective Date&quot;, and or take any other steps as required by any other applicable law and or laws..
        /// </summary>
        public static string privacyPagePara9Str {
            get {
                return ResourceManager.GetString("privacyPagePara9Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GustafU233C Privacy Policy:.
        /// </summary>
        public static string privacyPageTitle2Str {
            get {
                return ResourceManager.GetString("privacyPageTitle2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacyPageTitleStr {
            get {
                return ResourceManager.GetString("privacyPageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 06, 2023.
        /// </summary>
        public static string Proj1AboutPageLastModStr {
            get {
                return ResourceManager.GetString("Proj1AboutPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 06, 2023.
        /// </summary>
        public static string proj1CommonProbsUtf8SubNavLastModStr {
            get {
                return ResourceManager.GetString("proj1CommonProbsUtf8SubNavLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8 Problems.
        /// </summary>
        public static string proj1CommonProbsUtf8SubNavTitleStr {
            get {
                return ResourceManager.GetString("proj1CommonProbsUtf8SubNavTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 06, 2023.
        /// </summary>
        public static string Proj1EulaPageLastModStr {
            get {
                return ResourceManager.GetString("Proj1EulaPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 07, 2023.
        /// </summary>
        public static string Proj1HowToGenerallyPageLastModStr {
            get {
                return ResourceManager.GetString("Proj1HowToGenerallyPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To.
        /// </summary>
        public static string Proj1HowToGenerallyTitlePageStr {
            get {
                return ResourceManager.GetString("Proj1HowToGenerallyTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 07, 2023.
        /// </summary>
        public static string Proj1OpenPackages1PageLastModStr {
            get {
                return ResourceManager.GetString("Proj1OpenPackages1PageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Package One.
        /// </summary>
        public static string Proj1OpenPackages1TitlePageStr {
            get {
                return ResourceManager.GetString("Proj1OpenPackages1TitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 06, 2023.
        /// </summary>
        public static string Proj1PrivacyPageLastModStr {
            get {
                return ResourceManager.GetString("Proj1PrivacyPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 06, 2023.
        /// </summary>
        public static string Proj1TaConPageLastModStr {
            get {
                return ResourceManager.GetString("Proj1TaConPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: June 06, 2023.
        /// </summary>
        public static string Proj1TofServPageLastModStr {
            get {
                return ResourceManager.GetString("Proj1TofServPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string proj3Package1LastModStr {
            get {
                return ResourceManager.GetString("proj3Package1LastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string proj3Package1TitleStr {
            get {
                return ResourceManager.GetString("proj3Package1TitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string proj3Package2LastModStr {
            get {
                return ResourceManager.GetString("proj3Package2LastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string proj3Package2TitleStr {
            get {
                return ResourceManager.GetString("proj3Package2TitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string proj3Package3LastModStr {
            get {
                return ResourceManager.GetString("proj3Package3LastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string proj3Package3TitleStr {
            get {
                return ResourceManager.GetString("proj3Package3TitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string project1PageLastModStr {
            get {
                return ResourceManager.GetString("project1PageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 1.
        /// </summary>
        public static string project1PageTitleStr {
            get {
                return ResourceManager.GetString("project1PageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string project2PageLastModStr {
            get {
                return ResourceManager.GetString("project2PageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 2.
        /// </summary>
        public static string project2PageTitleStr {
            get {
                return ResourceManager.GetString("project2PageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string project3PageLastModStr {
            get {
                return ResourceManager.GetString("project3PageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 3.
        /// </summary>
        public static string project3PageTitleStr {
            get {
                return ResourceManager.GetString("project3PageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string project4PageLastModStr {
            get {
                return ResourceManager.GetString("project4PageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project 4.
        /// </summary>
        public static string project4PageTitleStr {
            get {
                return ResourceManager.GetString("project4PageTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date: July 20, 2023.
        /// </summary>
        public static string TaConPageEffectiveStr {
            get {
                return ResourceManager.GetString("TaConPageEffectiveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: July 20, 2023.
        /// </summary>
        public static string TaConPageLastModStr {
            get {
                return ResourceManager.GetString("TaConPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All content published and made available on Our Site is the property of GustafU233C and or the Site’s creators. This includes, but is not not limited to images, text, logos, documents, downloaded files and or anything that contributes to the composition of Our Site. With regard to the source code of Our Site, please see the applicable Licence section of Our Site for further clarification..
        /// </summary>
        public static string TaConPagePara10Str {
            get {
                return ResourceManager.GetString("TaConPagePara10Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes and or Modifications to these Terms and Conditions:.
        /// </summary>
        public static string TaConPagePara11Str {
            get {
                return ResourceManager.GetString("TaConPagePara11Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may update these Terms and Conditions from time to time, including to reflect changes to Our current practices and or for other operational, legal, and or regulatory reasons. We will post the revised Terms and Conditions on Our Site, update the &quot;Effective Date&quot;, and or take any other steps as required by any other applicable law and or laws..
        /// </summary>
        public static string TaConPagePara12Str {
            get {
                return ResourceManager.GetString("TaConPagePara12Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable Use:.
        /// </summary>
        public static string TaConPagePara13Str {
            get {
                return ResourceManager.GetString("TaConPagePara13Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a user of Our Site, you agree to use Our Site legally, not to use Our Site for illegal purposes and not to:.
        /// </summary>
        public static string TaConPagePara14Str {
            get {
                return ResourceManager.GetString("TaConPagePara14Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harass or mistreat other users of Our Site;.
        /// </summary>
        public static string TaConPagePara15Str {
            get {
                return ResourceManager.GetString("TaConPagePara15Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violate the rights of other users of Our Site;.
        /// </summary>
        public static string TaConPagePara16Str {
            get {
                return ResourceManager.GetString("TaConPagePara16Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violate the intellectual property rights of the Site’s owners and or any third party to the Site;.
        /// </summary>
        public static string TaConPagePara17Str {
            get {
                return ResourceManager.GetString("TaConPagePara17Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hack into the account of another user of the Site, and or the Site itself;.
        /// </summary>
        public static string TaConPagePara18Str {
            get {
                return ResourceManager.GetString("TaConPagePara18Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act in any way that could be considered fraudulent; and or.
        /// </summary>
        public static string TaConPagePara19Str {
            get {
                return ResourceManager.GetString("TaConPagePara19Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These terms and conditions (hereinafter referred to as the “Terms and Conditions”) govern the use of the website: https://gustafu233c.github.io/gustafu233c/ (hereinafter referred to as the “Site”). The Site is owned and operated by GustafU233C (hereinafter referred to as “We”, “Us”, and or “Our”). This Site is a blog, of sorts..
        /// </summary>
        public static string TaConPagePara1Str {
            get {
                return ResourceManager.GetString("TaConPagePara1Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post any material that may be deemed inappropriate, offensive, and or illegal..
        /// </summary>
        public static string TaConPagePara20Str {
            get {
                return ResourceManager.GetString("TaConPagePara20Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If We believe you are using Our Site illegally and or in a manner that violates these Terms and Conditions, We reserve the right to limit, suspend and or terminate your access to Our Site. We also reserve the right to take any legal steps necessary to prevent you from accessing Our Site..
        /// </summary>
        public static string TaConPagePara21Str {
            get {
                return ResourceManager.GetString("TaConPagePara21Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation of Liability:.
        /// </summary>
        public static string TaConPagePara22Str {
            get {
                return ResourceManager.GetString("TaConPagePara22Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GustafU233C and or Our directors, officers, agents, employees, subsidiaries, and or affiliates will not be liable for any actions, claims, losses, damages, liabilities, and or expenses, including legal fees, from your use of Our Site..
        /// </summary>
        public static string TaConPagePara23Str {
            get {
                return ResourceManager.GetString("TaConPagePara23Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indemnity:.
        /// </summary>
        public static string TaConPagePara24Str {
            get {
                return ResourceManager.GetString("TaConPagePara24Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Except where prohibited by law, by using Our Site, you indemnify and hold harmless GustafU233C and or Our directors, officers, agents, employees, subsidiaries, and or affiliates from any actions, claims, losses, damages, liabilities and or expenses, including legal fees, arising out of your use of Our Site and or your violation of these Terms and Conditions..
        /// </summary>
        public static string TaConPagePara25Str {
            get {
                return ResourceManager.GetString("TaConPagePara25Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispute Resolution:.
        /// </summary>
        public static string TaConPagePara26Str {
            get {
                return ResourceManager.GetString("TaConPagePara26Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject to any exceptions specified in these Terms and Conditions, if you and GustafU233C are unable to resolve any dispute through informal discussions, then you and GustafU233C agree to submit this issue before a mediator. The decision of the mediator will not be binding. Any mediator must be a neutral party acceptable to both you and GustafU233C..
        /// </summary>
        public static string TaConPagePara27Str {
            get {
                return ResourceManager.GetString("TaConPagePara27Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notwithstanding any other provision in these Terms and Conditions, you and GustafU233C agree that you both retain the right to bring an action in small claims court and or to bring an action for injunctive relief and or intellectual property infringement..
        /// </summary>
        public static string TaConPagePara28Str {
            get {
                return ResourceManager.GetString("TaConPagePara28Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severability:.
        /// </summary>
        public static string TaConPagePara29Str {
            get {
                return ResourceManager.GetString("TaConPagePara29Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read these Terms and Conditions. By using this Site, you indicate that you have read and understand these Terms and Conditions and agree to abide by them at all times. If you do not agree with the terms set out in these Terms and Conditions, do not use and or access Our Site..
        /// </summary>
        public static string TaConPagePara2Str {
            get {
                return ResourceManager.GetString("TaConPagePara2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If at any time any of the provisions set forth in these Terms and Conditions are found to be inconsistent and or invalid under applicable laws, those provisions will be deemed void and will be removed from these Terms and Conditions. All other provisions will not be affected by the removal, and the rest of these Terms and Conditions will still be considered valid..
        /// </summary>
        public static string TaConPagePara30Str {
            get {
                return ResourceManager.GetString("TaConPagePara30Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information Details:.
        /// </summary>
        public static string TaConPagePara31Str {
            get {
                return ResourceManager.GetString("TaConPagePara31Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should you have any questions and or concerns about Our Terms and Conditions and or privacy practices, and or if you would like to exercise any of the rights potentially available to you, please email Us at: GustafU233C@Protonmail.com..
        /// </summary>
        public static string TaConPagePara32Str {
            get {
                return ResourceManager.GetString("TaConPagePara32Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THESE TERMS AND CONDITIONS CONTAIN A DISPUTE RESOLUTION CLAUSE THAT IMPACTS YOUR RIGHTS ABOUT HOW TO RESOLVE DISPUTES. PLEASE READ THEM CAREFULLY!.
        /// </summary>
        public static string TaConPagePara3Str {
            get {
                return ResourceManager.GetString("TaConPagePara3Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governing Law:.
        /// </summary>
        public static string TaConPagePara4Str {
            get {
                return ResourceManager.GetString("TaConPagePara4Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The law governing these Terms and Conditions and or any dispute in relation to these Terms and Conditions will be the substantive law of the Province of Ontario, Canada, without regard to the choice of laws principles. In the context of these Terms and Conditions, a dispute is defined as, but not solely limited to, a disagreement and or lacking of agreement between parties, that may result in any sort of action, be that action legal in nature or otherwise..
        /// </summary>
        public static string TaConPagePara5Str {
            get {
                return ResourceManager.GetString("TaConPagePara5Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistic Interpretation of these Terms and Conditions:.
        /// </summary>
        public static string TaConPagePara6Str {
            get {
                return ResourceManager.GetString("TaConPagePara6Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These Terms and Conditions were originally prepared in the English language. Although GustafU233C may provide one or more translated versions of these Terms and Conditions, for your convenience, and or as required by municipal, and or provincial, and or state, and or federal law, it is very important to note that the English language version of these Terms and Conditions will always be the sole governing version of these Terms and Conditions, in the case of any conflict and or discrepancy and or dispute, le [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TaConPagePara7Str {
            get {
                return ResourceManager.GetString("TaConPagePara7Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With regard to gender in relation to the language used in these Terms and Conditions, please note that the headings used in these Terms and Conditions do not affect their interpretation. The use of any gender includes all genders. The singular includes the plural and vice-versa. Where a word and or phrase is defined, its’ other grammatical form and or forms have an equal and or corresponding meaning. If one gender has been utilized anywhere in these Terms and Conditions, this is just for simplicity purposes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TaConPagePara8Str {
            get {
                return ResourceManager.GetString("TaConPagePara8Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellectual Property:.
        /// </summary>
        public static string TaConPagePara9Str {
            get {
                return ResourceManager.GetString("TaConPagePara9Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GustafU233C Terms and Conditions:.
        /// </summary>
        public static string TaConPageTitle2Str {
            get {
                return ResourceManager.GetString("TaConPageTitle2Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TaConTitlePageStr {
            get {
                return ResourceManager.GetString("TaConTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: January 08, 2023.
        /// </summary>
        public static string TofServPageLastModStr {
            get {
                return ResourceManager.GetString("TofServPageLastModStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TofServTitlePageStr {
            get {
                return ResourceManager.GetString("TofServTitlePageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .NET Blazor.
        /// </summary>
        public static string topRowAboutDotnetStr {
            get {
                return ResourceManager.GetString("topRowAboutDotnetStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string topRowLanguageSelectStr {
            get {
                return ResourceManager.GetString("topRowLanguageSelectStr", resourceCulture);
            }
        }
    }
}
